# Configuration for the development environment
database:
  url: "postgres://admin:password123@postgres:5432/schema_api_db"

rabbitmq:
  url: "amqp://guest:guest@rabbitmq:5672/%2f"

api:
  host: "0.0.0.0"
  port: 8080